artifacts:
  - path: packages/feedstock/artifact
    name: installer

deploy:
  provider: S3
  access_key_id: $(ARTIFACTS_KEY)
  secret_access_key: $(ARTIFACTS_SECRET)
  bucket: $(ARTIFACTS_BUCKET)
  region: us-east-1
  set_public: true
  artifact: installer

environment:
  GIT_REPOSITORY: https://github.com/sci-bots/microdrop-3.0
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
      CONDA_CANARY: false

    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "64"
      CONDA_CANARY: false

init:
  - ECHO %PYTHON_VERSION% %MINICONDA%

install:
  # Configure GIT:
  - cmd: git config --global user.email "build@sci-bots.com"
  - cmd: git config --global user.name "Sci-Bots Builds"
  - cmd: git submodule update --init --recursive

  - # Setup Conda
  - cmd: set PATH=%MINICONDA%\bin;%MINICONDA%;%MINICONDA%\Scripts;%PATH%
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --add channels lucaszw
  - cmd: conda config --add channels sci-bots
  - cmd: conda update --yes --quiet conda
  - cmd: conda install --yes nsis nodejs=8.2.1 conda-build anaconda-client binstar constructor

  - # Run Tests
  - cmd: activate
  - cmd: node --version
  - cmd: npm install
  - cmd: npm install -g gulp
  - cmd: npm run test

  - # Build
  - cmd: npm run --prefix packages/feedstock install-pkgs
  # - cmd: ./node_modules/.bin/gulp --cwd packages/feedstock build
  - cmd: ./node_modules/.bin/gulp --cwd packages/feedstock construct

  - # Publish Conda Package
  - # XXX: Uploading with powershell raises error for no reason
  - # cmd: anaconda -t %ANACONDA_TOKEN% upload --force %CONDA_BLD_PATH%

build: false
test_script:
  - echo Build Complete
