artifacts:
  - path: packages/feedstock/artifacts/*.exe

deploy:
  provider: S3
  access_key_id: $(ARTIFACTS_KEY)
  secret_access_key: $(ARTIFACTS_SECRET)
  bucket: $(ARTIFACTS_BUCKET)
  region: us-east-1
  set_public: true
  artifact: installer

environment:
  GIT_REPOSITORY: https://github.com/sci-bots/microdrop-3.0

init:
  - ECHO %PYTHON_VERSION% %MINICONDA%

install:
  # Configure GIT:
  - cmd: git config --global user.email "build@sci-bots.com"
  - cmd: git config --global user.name "Sci-Bots Builds"
  - cmd: git submodule update --init --recursive

  - # Setup Conda
  - ps: Invoke-WebRequest "https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe" -OutFile "installer.exe"
  - cmd: dir
  - cmd: start /wait "" installer.exe /InstallationType=JustMe /RegisterPython=1 /S /D=%UserProfile%\Miniconda3
  - cmd: set PATH=%UserProfile%\Miniconda3\bin;%UserProfile%\Miniconda3;%UserProfile%\Miniconda3\Scripts;%PATH%
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --add channels lucaszw
  - cmd: conda config --add channels sci-bots
  - cmd: conda update --yes --quiet conda
  - cmd: conda install --yes nodejs=8 conda-build binstar constructor
  - cmd: conda install --yes Pillow
  - cmd: conda info

  - # Run Tests
  - cmd: activate
  - cmd: node --version
  - cmd: npm install
  - cmd: npm install -g gulp
  - cmd: npm run test

  - # Build
  - cmd: npm run --prefix packages/feedstock install-pkgs
  # - cmd: ./node_modules/.bin/gulp --cwd packages/feedstock build
  - cmd: ./node_modules/.bin/gulp --cwd packages/feedstock construct

  - # Publish Conda Package
  - # XXX: Uploading with powershell raises error for no reason
  - # cmd: anaconda -t %ANACONDA_TOKEN% upload --force %CONDA_BLD_PATH%

build: false
test_script:
  - echo Build Complete
