environment:
  GIT_REPOSITORY: https://github.com/sci-bots/microdrop-3.0

  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
      conda_recipe: microdrop-3-unstable-conda-recipe
init:
  - ECHO %PYTHON_VERSION% %MINICONDA%

install:
  # Configure GIT:
  - cmd: git config --global user.email "build@sci-bots.com"
  - cmd: git config --global user.name "Sci-Bots Builds"
 
  - # Build Conda package
  - cmd: git clone https://github.com/Lucaszw/microdrop-3-unstable-conda-recipe
  - cmd: set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
  - cmd: conda config --add channels sci-bots
  - cmd: conda install --yes conda-build anaconda-client binstar
  - ps: $env:MICRODROP_VERSION = git describe --tag
  - ps: $env:package_location = conda build $env:conda_recipe --output
  - ps: Write-Host $env:package_location
  
  - # XXX: Building using powershell raises error for no reason
  - cmd: conda build %conda_recipe%
  
  - # Publish Conda Package
  - # XXX: Uploading with powershell raises error for no reason
  - cmd: anaconda -t %binstar_token% upload --force %package_location%

build: false
test_script:
  - echo Build Complete
