environment:
  GIT_REPOSITORY: https://github.com/sci-bots/microdrop-3
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
      CONDA_CANARY: false

    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
      CONDA_CANARY: false

init:
  - ECHO %PYTHON_VERSION%
  - Install-Product node ''

install:
  # Run Tests
  - cmd: node --version
  - cmd: npm i --global yarn
  - cmd: yarn global add lerna npm-check-updates
  - cmd: yarn run bootstrap
  - cmd: yarn run build
  - cmd: yarn run test


build: false
test_script:
  - echo Build Complete
