environment:
  GIT_REPOSITORY: https://github.com/sci-bots/microdrop-3.0

  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
      nodejs_version: "8"

init:
  - ECHO %PYTHON_VERSION% %MINICONDA%

install:
  # Configure GIT:
  - cmd: git config --global user.email "build@sci-bots.com"
  - cmd: git config --global user.name "Sci-Bots Builds"
  # Install Node/NPM
  - cmd: choco install nodejs
  - cmd: node --version
  - cmd: npm --version
  # Configure NPM, and Publish
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - cmd: npm whoami
  - cmd: npm version patch
  - cmd: npm publish .
  # Build Conda package
  - cmd: setx path "%path%;%MINICONDA%"
  - cmd: setx path "%path%;%MINICONDA%\\Scripts"
  - cmd: git clone https://github.com/Lucaszw/microdrop-3-conda-recipe
  - cmd: conda build .\microdrop-3-conda-recipe

build: false
test_script:
  - echo Build Complete
