artifacts:
  - path: packages/feedstock/artifacts/*.exe
    name: MicrodropInstaller

deploy:
  provider: S3
  access_key_id: $(ARTIFACTS_KEY)
  secret_access_key: $(ARTIFACTS_SECRET)
  bucket: $(ARTIFACTS_BUCKET)
  region: us-east-1
  set_public: true
  artifact: MicrodropInstaller
  unzip: true

environment:
  GIT_REPOSITORY: https://github.com/sci-bots/microdrop-3
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
      CONDA_CANARY: false

    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
      CONDA_CANARY: false

init:
  - ECHO %PYTHON_VERSION%

install:
  # Configure GIT:
  - cmd: git config --global user.email "build@sci-bots.com"
  - cmd: git config --global user.name "Sci-Bots Builds"
  - cmd: git submodule update --init --recursive

  # Setup Conda (Must install in User directory for constructor to work)
  - cmd: set PATH=%MINICONDA%\bin;%MINICONDA%;%MINICONDA%\Scripts;%PATH%
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --add channels lucaszw
  - cmd: conda config --add channels sci-bots
  - cmd: conda update --yes --quiet conda
  - cmd: conda install --yes nodejs=8 binstar
  - cmd: conda install --yes --channel anaconda conda-build constructor
  - cmd: conda install --yes Pillow
  - cmd: conda info

  # Run Tests
  - cmd: activate
  - cmd: node --version
  - cmd: npm install --global gulp
  - cmd: npm install --global --production windows-build-tools
  - cmd: npm install
  - cmd: npm run test
  - cmd: set
  # Build
  - cmd: npm run --prefix packages/feedstock install-pkgs
  - cmd: ./node_modules/.bin/gulp --cwd packages/feedstock build
  - cmd: ./node_modules/.bin/gulp --cwd packages/feedstock construct

build: false
test_script:
  - echo Build Complete
