package:
    name: microdrop-app
    version: 1.1.2
source:
    git_url: .
requirements:
    build:
        - 'nodejs >=8'
    run:
        - 'nodejs >=8'
build:
    script: 'npm install & .\node_modules\.bin\gulp conda:build'
about:
    home: 'https://github.com/sci-bots/microdrop-3'
    license: BSD
    license_file: LICENSE
