[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "dropbot_plugin"
author = "Sci-Bots"
author-email = "info@sci-bots.com"
home-page = "http://sci-bots.com"
license = "BSD-2-Clause"
requires = ["micropede"]
